sudo: true

language: cpp

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install csh; fi

# command to run tests
script: 
  - export ROOT=`pwd`
  - make
  - make testing
  
after_success:
  - bash <(curl -s https://codecov.io/bash)